version: 2.1

orbs:
  preevy: livecycle/preevy@0.0.1

# Define the jobs we want to run for this project
jobs:
  deploy_preview:
    executor: preevy/default
    steps:
      - preevy/install
      - preevy/init:
          profile_url: "s3://preevy-297324796627-test3?region=eu-west-1"
      - checkout
      - preevy/up:
          docker-compose-yaml-path: "./production/docker-compose.yaml"
# Orchestrate our job run sequence
workflows:
  deploy_preview:
    jobs:
      - deploy_preview
