version: 2.1

orbs:
  preevy: livecycle/preevy@0.0.1
  aws-cli: circleci/aws-cli@3.1.5

# Define the jobs we want to run for this project
jobs:
  deploy_preview:
    environment:
        AWS_REGION: us-west-1
    executor: preevy/default
    steps:
      - run: sudo npm i -g preevy
      - aws-cli/setup:
          role-arn: "arn:aws:iam::297324796627:role/loki-circleci"
          aws-region: AWS_REGION
      - preevy/init:
          profile_url: "s3://preevy-297324796627-test3?region=eu-west-1"
      - checkout
      - preevy/up:
          docker_compose_yaml_path: "./production/docker-compose.yaml"
# Orchestrate our job run sequence
workflows:
  deploy_preview:
    jobs:
      - deploy_preview
