name: Teardown Preevy environment
on:
  pull_request:
    types:
      - closed
env:
  AWS_REGION: "eu-west-1"
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::297324796627:role/loki-github-action
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/checkout@v3
      - uses: livecycle/preevy-down-action@latest
        id: preevy
        with:
          profile-url: "s3://preevy-297324796627-test3?region=eu-west-1"
          args: "-f ./production/docker-compose.yaml"