name: Deploy Preevy environment - with new action
on:
  pull_request:
    types:
      - opened
      - synchronize
env:
  AWS_REGION: "us-east-1"
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::297324796627:role/loki-github-action
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/checkout@v3
      - uses: livecycle/gh-action-preevy@v0.0.1-alpha
        with:
          profile-url: "s3://preview-297324796627-gh-action?region=us-east-1"
          command: "up"
          args: "-f ./production/docker-compose.yaml"
