name: Deploy Preevy environment
on:
  pull_request:
    types:
      - opened
      - synchronize
env:
  AWS_REGION: "us-east-1"
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::297324796627:role/loki-github-action
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/checkout@v3
      - name: Install Preevy CLI
        run: npm i -g preevy
      - name: Run preevy up
        run: |
          preevy init --from "s3://preview-297324796627-gh-action?region=us-east-1"
          cd production
          preevy up --log-level debug
      - name: output URLs
        id: output_urls
        run: |
          export urls_table=$(cat << EOF
          | Service | Port | URL |
          |---------|------|-----|
          $(preevy urls --json | jq -r '.[] | {service, port, url} | join(" | ") | "| " + . + " |" ')
          EOF)
          echo "urls_table=$urls_table" >> "$GITHUB_OUTPUT"
      - name: Create PR comment with URLs
        # uses: octokit/request-action@v2.1.0
        # with:
        #   route: GET /repos/{owner}/{repo}/releases/latest
        #   owner: octokit
        #   repo: request-action
        run: |
          echo "${{ steps.output_urls.outputs.urls_table }}""